### ISSUE TITLE
./install script gets stuck with neovim

### ISSUE THREAD

**Issue by albertoleal** [luan/vimfiles#100]
Hi @luan !

I'm configuring a brand new machine with Sierra (10.12.5) and neovim (stable 0.2.0 - tried HEAD as well), and when I ran the install script it gets stuck either on "Updating plugins" or  "Installing go binaries". Have you seen that before? Do you have any idea what might be causing that?

This problem does not happen if I use `vim` instead.

Thanks,
Alberto

**Comment by Infra-Red** [comment]
I've observed the same issue with neovim, works fine when passing `--non-interactive` option.

**Comment by albertoleal** [comment]
Thanks @Infra-Red ! 

I was able to reproduce that 100%, but out of a blue the problem no longer happens.
