### ISSUE TITLE
errors / linter messages don't show on Linux

### ISSUE THREAD

**Issue by craigfurman** [luan/vimfiles#103]
Observed on both Arch and Ubuntu 16.04.

In 5ca8e94, the switch to ale resulted in the quickfix not popping up. This isn't unexpected, it's a non-default config option for ale to use the quickfix. At a glance all seems good here but I didn't use this SHA for long, only to investigate the error I'm getting now.

Since be705ba (the switch back to neomake), I get no errors / linter messages at all, in any language. This occurs from both an upgrade, and a fresh install.

Please let me know if there's any more information I can get for you. I know shockingly little about vim mainly due to blindly relying on this excellent config! :smile:

**Comment by craigfurman** [comment]
Forgot to say, I'm not 100% sure if the problem is occurring on macOS. I think someone told me it wasn't but I've been away from a mac all day

**Comment by jszroberto** [comment]
Same happened to me on Mac OS. I needed to checkout back to c217ebd85aaf462803526ae5997d014a15b050a3

**Comment by luan** [comment]
Fixed on master, sorry for the inconvenience!
