### ISSUE TITLE
gometalinter not found

### ISSUE THREAD

**Issue by ablease** [luan/vimfiles#111]
On fresh install (go already installed on this machine) getting a problem when installing
`.vim/install: line 272: /Users/alex/.vim/gobin/gometalinter: No such file or directory`
I took a look in `.vim/gobin/` and there are no go binaries in there....

Will take a look when I get home just about to leave the office.

**Comment by luan** [comment]
Huh, did you run the installer?

**Comment by ablease** [comment]
This was a problem with nvim I think. After i removed nvim and cleaned all its config and reinstalled, the install script worked. :)

**Comment by luan** [comment]
That's weird. Should totally work with nvim. Do you have the logs from that installation?

**Comment by a-b** [comment]
@luan deleting ~/.config/nvim/ folder solves this issue.
