### ISSUE TITLE
fresh install on macOS High Sierra fails on gocode

### ISSUE THREAD

**Issue by rosenhouse** [luan/vimfiles#121]
Not sure what this is about....
```
dial unix .../gocode-daemon.pivotal: connect: no such file or directory
```

Should I install `github.com/mdempsky/gocode` before running `install` here?

**Comment by rosenhouse** [comment]
so

```
go get -u github.com/nsf/gocode
```
seems to help get past that error, but then I hit:
```
rpc: can't find service Server.Exit
```

Seems like some dependency added a dependency?

**Comment by luan** [comment]
@rosenhouse is this on latest go? Who's giving you that error? Installation or opening vim?
Vim version?

**Comment by rosenhouse** [comment]
Occurs on install.  Line immediately above the error message is 
```
DONE go binaries
```

go 1.10.2

NVIM v0.2.2

**Comment by leeloodub** [comment]
Luan, thank you for looking into the issue. Seems like the issue persists. I had to clone the repo, delete 
```
  GOPATH="${PWD}/gopath" GOBIN="${PWD}/gobin" "${PWD}/gobin/gocode" drop-cache
```
and run the ./install . Not sure if this will cause any further problems, but works so far. 

Thank you.

**Comment by luan** [comment]
@leeloodub can you show me what error you see? It might just be a warning message that is misleading you. Are you sure `./install` isn't exiting 0?
