### ISSUE TITLE
yarn asked to be installed as a dependency - I don't do javascript

### ISSUE THREAD

**Issue by zachgersh** [luan/vimfiles#137]
pretty consistent `yarn` nag happening even though the files i am loading are in no way jabascript related:

```sh
nvim config dependency `yarn` not installed and is requred.
Error detected while processing function <SNR>3_checkDependencies:
line    4:
Missing dependencies detected. Please refer to the README for more information on how to install them.
Press ENTER or type command to continue
```

I haven't actually dug into _why_ but wanted this issue to be a record.

**Comment by zachgersh** [comment]
@luan do you think there is a way to only ask for `yarn` if / when you open a js file?

**Comment by luan** [comment]
@zachgersh you probably meant to open this issue on https://github.com/luan/nvim

On that newer repo `yarn` is used for setting up the language server integrations and not only for javascript. See https://github.com/luan/nvim#installation for a short explanation of each dependency.
