### ISSUE TITLE
Automatic Go Formatting breaks repeat behaviour

### ISSUE THREAD

**Issue by xoebus** [luan/vimfiles#31]
I saw you had a commit to fix this but it was reverted?

**Comment by luan** [comment]
Yes, the "fix" was to revert back to the old go-fmt plugin, which is madly slow in some codebases (i.e. diego). I'll find a better way to get this fixed soon, sorry!

**Comment by luan** [comment]
Keeping this open for tracking of this.

**Comment by luan** [comment]
This is actually fixed on eb570201fd7d51b4a75d709fa8a6899cb4044203.
