### ISSUE TITLE
I broke vim

### ISSUE THREAD

**Issue by cwlbraa** [luan/vimfiles#32]
while trying to open a file using control-p fuzzy-find with a line number where neither the file or its parent directory exists

```
/tmp/build/47526685-f349-4eba-548b-40ee6df0bb53/diego-release/src/github.com/cloudfoundry-incubator/inigo/cell/task_test.go:222
```

results in:
```
Vim: Caught deadly signal SEGV

Vim: Finished.
Segmentation fault: 11
```

**Comment by luan** [comment]
Weird Ctrl-P behavior, only reproducible if you paste a long string, probably not worth spending too much time on. Closing this.
