### ISSUE TITLE
vim-go function/struct highlighting is slow

### ISSUE THREAD

**Issue by krishicks** [luan/vimfiles#35]
I had to disable it: https://github.com/krishicks/vimfiles/commit/e348bd7cfd2635f3a6937a8eba6972a36e5ad76e

This was problematic on test files particularly because they can grow to be quite large. My 2015 MacBook struggled to move the pointer around on larger files. Disabling both of these functions fixed the performance problem.

These flags are used here: https://github.com/fatih/vim-go/blob/3df3cbf2e7ab9d76fd67f9f4077060b4450ba90c/syntax/go.vim#L268

Maybe the regex could be optimized for performance.

For now, I don't care so much about the function and struct highlighting, so disabling works for me.

**Comment by luan** [comment]
I did the same + methods: https://github.com/luan/vimfiles/commit/44e5fafa7223c4df70a99e70b5b97c6703c69611
