### ISSUE TITLE
AutoCloseOn no workie

### ISSUE THREAD

**Issue by wendorf** [luan/vimfiles#49]

**Comment by luan** [comment]
There was an issue with it before that caused you to have to hit `Esc` twice when you had an autocomplete window open. Would have to also solve that.
Also, got `AutoCloseOn` to work here by enabling it and reloading the buffer(`:edit`). Seems like it doesn't enable dynamically when you do `:AutoCloseOn` while already having buffers open.

**Comment by luan** [comment]
I've removed AutoClose entirely now. I'm interested in seeing if folks are actually using it, if they're I can try to come up with a better solution in general since this plugin conflicts too much with other things.
