### ISSUE TITLE
maktaba error on vim startup

### ISSUE THREAD

**Issue by joshq00** [luan/vimfiles#50]
After doing a brew update/upgrade, I now see this error every time I start vi
```
ERROR(BadValue): Dictionary with keys ['dict', 'func', 'Apply', 'Call', 'WithContext', 'arglist', 'WithArgs'] is not a maktaba function.
```
I have to press enter to continue... Every time.

If I use `nvim` I don't see any errors.

List of (possibly?) relevant brew items installed
```sh
$ brew list --versions
gnu-indent 2.2.10
gnutls 3.4.10 3.4.9
go 1.6
macvim 7.4-96 7.4-97 7.4-99
neovim 0.1.2
python 2.7.11
python3 3.5.1
ruby 2.3.0
taglib 1.10
universal-ctags HEAD
vim 7.4.1345 7.4.1401 7.4.1589
```

I don't know anything about maktaba and I couldn't figure out how to get it to log/debug :disappointed:

**Comment by luan** [comment]
Hi @joshq00,

Thanks for reporting this, but it seems like you were using a previous commit of the vimfiles itself, by the time you created this issue, I had temporarily disabled "maktaba" and the packages that depend on it temporarily while I looked at solving the issue.

It would seem that now the issue has been resolved. I re-enabled those plugins, run a `~/.vim/update` to get the latest versions. You might also want to upgrade your vim again (I've now got patch 1655).

Could you try that?

**Comment by joshq00** [comment]
I'll give it a shot and update the issue with my findings.

Thanks, btw. This repo rules

**Comment by joshq00** [comment]
You are correct: no more error! Thanks!
