### ISSUE TITLE
:GoReference -> minibuf -> enter explodes in my face

### ISSUE THREAD

**Issue by cwlbraa** [luan/vimfiles#58]
please, I only want to browse source code backwards. 

Looking for where a Golang func is called and then pressing enter over the file I want to go to gives me:
```
Error detected while processing function CRWriteIfNecessary:
line    3:
E924: Current window was closed
Press ENTER or type command to continue
```

**Comment by cwlbraa** [comment]
the change you made broke saving go files

**Comment by luan** [comment]
I believe this is fixed now, can you verify?
