### ISSUE TITLE
"Simple install" doesnt work

### ISSUE THREAD

**Issue by benmoss** [luan/vimfiles#73]
The `Installation` instructions of just curling that script don't really work. I think they assume you have already cloned the repo.

**Comment by luan** [comment]
Thanks @benmoss, that's a good point.
Think I fixed this just now on 001dfa1b9. Can you check if that works for you?

**Comment by benmoss** [comment]
It now symlinks your current directory to `~/.vim` if your current directory has a `.git` directory :)

I think your script needs more control over its working directory or you should add some instructions on where you should run it from. Like unless you want to get into the whole `mv ~/.vim{,.old}` business, maybe just tell people "yo make a clean `~/.vim` dir, cd there, and then totally eval this dope script from the internet

**Comment by luan** [comment]
@benmoss I rewrote the whole install script basically. It should be a little smarter about directories now but I haven't extensively tested that many edge cases. Let me know if that helps your issue.

**Comment by benmoss** [comment]
```
○ → curl vimfiles.luan.sh/install | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6146  100  6146    0     0   305k      0 --:--:-- --:--:-- --:--:--  315k
Detected non-interactive shell, forcing --non-interactive
/Users/pivotal/.vim belongs to a repository other than . Move it away and re-run this scripts. Aborting...
```

**Comment by benmoss** [comment]
Seems like something wrong with `should_clone`, my bash skills suck too much to be of much help

**Comment by luan** [comment]
Alright, should actually work now.

**Comment by luan** [comment]
I did that logic completely wrong the first time around.

**Comment by benmoss** [comment]
Yup, seems to work now! 👌
