### ISSUE TITLE
Error when yanking to clipboard

### ISSUE THREAD

**Issue by albertoleal** [luan/vimfiles#75]
Hi @luan!

After upgrading to the newest version we've started seeing some failures when yanking to clipboard (shift +y):

The error does not give us any hint what's going on: `clipboard: error:`

This issue happens only when yanking inside a `tmux` session. We're using your `tmux.conf` (https://github.com/luan/dotfiles/blob/master/tmux.conf). It works in a "regular" bash session.

Have you seen this before? Do you have any idea what may be the problem? 

(we've install all tpm plugins)

thanks,

**Comment by luan** [comment]
What OS are you using @albertoleal?

**Comment by albertoleal** [comment]
@luan It's on Mac OS Sierra, with neovim

**Comment by luan** [comment]
Sierra broke this, you now need `reattach-to-user-namespace` again. `brew install reattach-to-user-namespace` and updating the tmux config should work.

**Comment by albertoleal** [comment]
Thank you, @luan!
