### ISSUE TITLE
Unable to imap jj or jk to escape Insert mode.

### ISSUE THREAD

**Issue by pavlvs** [luan/vimfiles#79]
Neither _imap jj_`<ESC>` nor _imap jk_`<ESC>` or any other 2 character combination work for me to escape Insert mode.

**Comment by luan** [comment]
`jk` is actually already mapped. You should know that multi-key bindings have to be pressed fairly quickly as we have a 100ms timeout set for keybindings by vim-sensible [here](https://github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim#L28). I just tested that the binding works on both vim and neovim.
