### ISSUE TITLE
`:Ctags` command does not generate ctags for current ruby project

### ISSUE THREAD

**Issue by zaksoup** [luan/vimfiles#81]
Using latest config in neovim: I have to run `:!ctags -R` (or something, can never remember if it's `-r` or `-R` or `-r/R .` etc)

**Comment by zaksoup** [comment]
til it's rtags

**Comment by zaksoup** [comment]
<img width="303" alt="screen shot 2017-01-11 at 9 59 42 am" src="https://cloud.githubusercontent.com/assets/296065/21860258/c00fc62e-d7e4-11e6-969c-c3895a5ae39c.png">

**Comment by luan** [comment]
You need to have a ruby file opened.

**Comment by zaksoup** [comment]
using neovim, if that makes any difference :man_shrugging:
<img width="381" alt="screen shot 2017-01-11 at 3 18 59 pm" src="https://cloud.githubusercontent.com/assets/296065/21870466/59c4214e-d811-11e6-8cc6-7c2b646ebecb.png">
