### ISSUE TITLE
Error related to markdown.vim and syntax/elm.vim

### ISSUE THREAD

**Issue by sergueif** [luan/vimfiles#95]
Error while opening a `.md` file:

```
Error detected while processing /usr/local/Cellar/vim/8.0.0596/share/vim/vim80/syntax/markdown.vim:
line   25:
E484: Can't open file syntax/elm.vim
```

as of writing version of macOS, brew-installed vim.

**Comment by sergueif** [comment]
Hey @luan . You can probably just close this. It was a result of not running `vim-update` after installing.

**Comment by luan** [comment]
Thanks @sergueif
